repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: detect-private-key
    - id: forbid-new-submodules
    - id: check-builtin-literals

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: forbid-binary
    - id: git-dirty

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
    - id: forbid-crlf
    - id: remove-crlf

- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.25.0
  hooks:
    - id: commitizen
      stages: [commit-msg]

- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.362
  hooks:
    - id: pyright

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.3
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format
