name: main
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container: python:3.12-slim-bullseye
    steps:
    - uses: actions/checkout@v4
      with:
        set-safe-directory: true
    - uses: pre-commit/action@v3.0.1
