name: Upload Python Package
on:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: python:3.12-slim-bullseye
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        pip install -U pip poetry
        poetry install
    - name: Publish package to testpyi
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry config pypi-token.testpypi $(echo $POETRY_PYPI_TOKEN_TEST)
        poetry publish --build --repository testpypi
      env:
        POETRY_PYPI_TOKEN_TEST: ${{ secrets.POETRY_PYPI_TOKEN_TEST }}
