name: Upload To PyPi
on:
  push:
    tags:
    - "*"
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      - name: Publish package to testpyi
        run: |
          pip install -U pip poetry
          poetry install --sync
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi $(echo $POETRY_PYPI_TOKEN_TEST)
          poetry publish --build --repository testpypi
        env:
          POETRY_PYPI_TOKEN_TEST: ${{ secrets.POETRY_PYPI_TOKEN_TEST }}
