name: pre-commit
on:
  pull_request:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        set-safe-directory: true
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip
    - run: |
        pip install deptry
    - uses: pre-commit/action@v3.0.1
