name: tests
permissions:
  actions: read
  contents: read
  issues: write
  pull-requests: write
on:
  pull_request:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']  # List Python versions here
    steps:
    - uses: actions/checkout@v4
      with:
        set-safe-directory: true
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install dependencies and run tests
      run: |
        pip install -U pip poetry
        poetry install --sync -E togetherai
        poetry run coverage run -m unittest discover
        poetry run coverage report --format=markdown > report.txt
    - name: Report Coverage
      uses: actions/github-script@v7
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        script: |
          const fs = require('fs');
          const coverage = fs.readFileSync('./report.txt', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: coverage
          })
