name: tests
permissions:
  actions: read
  contents: read
  issues: write
  pull-requests: write
on:
  pull_request:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        set-safe-directory: true
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip
    - name: tests
      run: |
        pip install -U pip poetry deptry
        poetry install --sync
        poetry run deptry .
        poetry run coverage run -m unittest discover
        poetry run coverage report --format=markdown > report.txt
    - name: Report Coverage
      uses: actions/github-script@v7
      github-token: ${{secrets.GITHUB_TOKEN}}
      with:
        script: |
          const fs = require('fs');
          const coverage = fs.readFileSync('./report.txt', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: coverage
          })
